services:
    netgen_block_manager.collection.query_type.handler.ezcontent_relation_list:
        class: Netgen\Layouts\RelationListQuery\Handler\RelationListQueryHandler
        public: false
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_block_manager.ezpublish.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@netgen_block_manager.ezpublish.content_provider"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_block_manager.collection.query_type_handler, type: ezcontent_relation_list }
