services:
    netgen_layouts.relation_list_query.handler:
        class: Netgen\Layouts\Ez\RelationListQuery\Handler\RelationListQueryHandler
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_layouts.ezplatform.search_service"
            - "@netgen_layouts.ezplatform.content_provider"
            - "@ezpublish.config.resolver"
        tags:
            - { name: netgen_layouts.query_type_handler, type: ezcontent_relation_list }
